# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'hW2.8' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

end
